path_classifiers:
  generated:
    - exclude: "build/*.java"
queries:
  - include: "*"
  - exclude: java/index-out-of-bounds
  - exclude: java/local-shadows-field
  - exclude: java/missing-override-annotation
  - exclude: java/non-static-nested-class
  - exclude: java/potentially-weak-cryptographic-algorithm
  - exclude: java/uncaught-number-format-exception
  - exclude: java/unused-parameter
  - exclude: py/empty-except
  - exclude: py/redundant-global-declaration
extraction:
  java:
    prepare:
      packages:
        - python3.8
    index:
      build_command:
        - python3.8 build.py
      java_version: 1.8
      xml_mode: disabled
  python:
    python_setup:
      version: 3
